### ISSUE TITLE
Verbose flag to git commit breaks git cop

### ISSUE THREAD

**Issue by akupila** [bkuhlmann/git-cop#30] opened 2017-10-24 04:54 UTC
## Overview
Git commit has [a verbose flag](https://git-scm.com/docs/git-commit#git-commit--v) which shows a diff of what's about to be committed in below the actual commit message. This is quite useful as you can quickly scan through the changes, in order to ensure everything is captured in the commit message.

However, this additional information (which is ignored by git) confuses git cop and essentially breaks running git cop as a precommit hook.

## Steps to Recreate
1. Set up git cop as a precommit hook on a git repo in `.git/hooks/commit-msg`:
```
#! /usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail
IFS=$'\n\t'

if ! command -v git-cop > /dev/null; then
   printf "%s\n" "[git]: Git Cop not found. To install, run: gem install git-cop --trust-policy MediumSecurity."
   exit 1
fi

git-cop --hook --commit-message "${BASH_ARGV[0]}"
```
2. Create a new file in the repo, add some text to it
3. `git add *`
4. `git commit -v`

Notice that the git commit message includes the following (known as a `scissor` in git):

```
# ------------------------ >8 ------------------------
# Do not touch the line above.
# Everything below will be removed.
```

However, saving the changes, git cop still tries to analyze the diff below which most certainly won't match the rules.

## Desired:

Git cop ignores everything below the scissors marker (`------------------------ >8 ------------------------`).

_I would do a PR but my ruby skills are close to zero :( I would expect this to be a quick for for somebody else wanting to contribute to the project though_

**Comment by akupila** [comment] 2017-10-24 05:10
I noticed that the [readme actually recommends](https://github.com/bkuhlmann/git-cop#post-commit) using a `post-commit` hook which doesn't break this functionality since git strips the scissor marker before. I've switched to using this instead, feel free to close the issue.

**Comment by bkuhlmann** [comment] 2017-10-25 12:09
Good catch. Thanks for finding this. I'm going to investigate as it would be nice to resolve this for the `commit-msg` hook. ...but, yes, the workaround you mentioned will get you by in the meantime.

**Comment by bkuhlmann** [comment] 2017-10-29 22:52
@akupila Looked into this more and am not able to reproduce. Here are the steps I'm using:

```
mkdir tester
cd tester
git init
git checkout -b test
touch example.txt
git add --all .
git commit -v
```

At this point I add the following text within my editor: "Added example file." I save and close, which yields the following output:

```
Running Git Cop...
1 commit inspected. 0 issues detected.
[ctags]: CTags rebuilt.
[test (root-commit) 0184511905d0] Added example file.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 example.txt
```

There are no errors with Git Cop even though, I see the scissors comment line. ...but it is a comment line which Git Cop ignores by default.

I tested this with *Git Cop 1.6.2*. Do you experience the same issue with this version as well?

**Comment by akupila** [comment] 2017-10-30 09:59
I'm currently not able to run git cop (different machine) but i think one thing that's missing from your test above some actual content in the `example.txt` file. If you only `touch` it, it will be empty and the diff won't show up with `git commit -v`. The scissors itself is a comment, but the diff is not. Maybe try `echo "this is a test" > example.txt` before adding the file, to see if that changes things? Sorry for not providing better steps to reproduce before… 😞 

I also realized i probably didn't run this on the latest version of git cop. I'll check again when i'm on the machine with this set up

**Comment by bkuhlmann** [comment] 2017-10-30 13:37
Ah, thanks, I see the issue now. Forgot about how that worked and what the generated Git diff looks like in the commit message. It happens in all versions so no need to worry about using the latest version. Yeah, this is a bug that I'll work on fixing.

**Comment by bkuhlmann** [comment] 2017-11-05 18:11
What version of Git are you using?

```
git --version
git version 2.15.0
```

In a strange turn of events, I was able to recreate this issue using Git 2.14.0 but after upgrading to Git 2.15.0, it seems Git is respecting `git commit -v` properly now which does not interfere with Git Cop's parsing of the file contents. Is this the case for you as well?

**Comment by akupila** [comment] 2017-11-05 18:33
```
git --version
git version 2.12.2
```

Interesting, should try to upgrade.

That said, I actually prefer the post commit hook. With a precommit if i make a typo or something else that breaks the rules, i'm forced to retype the entire message. Now i'll just `--amend` instead

**Comment by bkuhlmann** [comment] 2017-11-05 20:06
Actually, that is a bit of a misnomer:

> With a precommit if i make a typo or something else that breaks the rules, i'm forced to retype the entire message.

The reason is that if the Git Hook fails, for whatever reason, what you typed in the commit message is never lost. It's actually stored in the project's `.git/COMMIT_EDITMSG` file. I've been thinking I should maybe include that as a tip in the Git Cop output upon error at some point. Using an editor like Sublime Text, for example, you can hit `COMMAND+SHIFT+T` to re-open the last file that you were editing (i.e. `.git/COMMIT_EDITMSG`) and easily copy your original message and make a new one. You're info is never lost. Git is pretty good about that. 😄 

Sounds like you have a workflow you enjoy, which is good. I'm going to close this issue for now but plan to add some safety precautions to the gem in the future.

**Closed by bkuhlmann** 2017-11-05 20:06 UTC
Labels: bug

**Comment by akupila** [comment] 2017-11-05 20:11
Oh, that's very useful, didn't know that. Thanks!

Yes i'm happy with the workflow now, thanks for the conversations here and all the effort on Git Cop ⭐️

**Comment by bkuhlmann** [comment] 2017-11-05 20:18
Yeah, you bet. This was good feedback too. Enjoy!
